name: df-voice-env
channels:
  - defaults
  - pytorch
dependencies:
  - python==3.7
  - pip==20.0.2
  - pytorch==1.4.0
  - pip:
    - tensorflow-gpu==1.14.0
    - umap-learn==0.4.1
    - visdom==0.1.8.9
    - webrtcvad==2.0.10
    - librosa==0.7.2
    - matplotlib==3.2.1
    - numpy==1.18.3
    - scipy==1.4.1
    - tqdm==4.45.0
    - sounddevice==0.3.15
    - Unidecode==1.1.1
    - inflect==4.1.0
    - PyQt5==5.14.2
    - multiprocess==0.70.9
    - numba==0.49.0